name: GHA Workflow Validation

on:
  pull_request:
  merge_group:

jobs:
  validate-workflows:
    name: Validate Workflow Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    # Skip on merge group events
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      # checkout repo if not pull_request trigger (disabled for now)
      - name: Checkout Repo
        if: github.event_name != 'pull_request'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run gha-workflow-validator action
        uses: smartcontractkit/.github/actions/gha-workflow-validator@93b85b44646131696b18994c9cc0ad572c4102af # gha-workflow-validator@0.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          evaluate-mode: true
